import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Boxes, CheckCircle2, ClipboardList, ExternalLink, HandHeart, LayoutDashboard, LogIn, PackageCheck, PackageOpen, Truck, UserRoundPlus, Users } from 'lucide-react';

const steps = [
  ['Registrar al donante', 'Cargá los datos necesarios de cada persona u organización que acerca una donación.', UserRoundPlus],
  ['Catalogar los insumos', 'Detallá qué se recibió, su categoría y cantidad para mantener la información ordenada.', PackageOpen],
  ['Preparar el inventario', 'Consultá las existencias y actualizá el estado de los insumos antes de su despacho.', Boxes],
  ['Registrar el envío', 'Dejá asentado qué ayuda sale, hacia dónde se dirige y cuándo inicia su recorrido.', Truck],
];
const benefits = [
  ['Una operación más clara', 'La información importante se organiza en un único espacio de trabajo.', LayoutDashboard],
  ['Menos tareas repetidas', 'Cada registro queda disponible para todo el equipo autorizado.', ClipboardList],
  ['Mejor preparación', 'El estado del inventario ayuda a coordinar la ayuda antes de cada envío.', PackageCheck],
];

export default function Landing() {
  return <div className="min-h-screen bg-[#F4F6F7] text-[#1B2631]">
    <style>{`html{scroll-behavior:smooth}.landing-grid{background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px);background-size:54px 54px}`}</style>
    <header id="inicio" className="relative overflow-hidden bg-[#1B2631] text-white">
      <div className="landing-grid absolute inset-0" /><div className="absolute -right-40 top-16 h-[34rem] w-[34rem] rounded-full bg-[#E34E26]/15 blur-3xl" />
      <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-8">
        <a href="#inicio" className="inline-flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E34E26]"><HandHeart size={21} /></span><span><b className="block text-lg leading-tight">Acción del Sur</b><small className="block font-bold uppercase tracking-[.18em] text-white/55">CGIC · Gestión interna</small></span></a>
        <div className="flex items-center gap-6"><a href="#funcionalidades" className="hidden font-bold text-white/70 sm:block">Funcionalidades</a><a href="https://cgic-argentina.org/" target="_blank" rel="noreferrer" className="hidden items-center gap-1.5 font-bold text-white/70 hover:text-white md:inline-flex">Conocé CGIC <ExternalLink size={14} /></a><Link to="/login" className="inline-flex items-center gap-2 rounded-xl border border-white/25 bg-white/10 px-4 py-2.5 font-extrabold"><LogIn size={17} /> Iniciar sesión</Link></div>
      </nav>
      <div className="relative z-10 mx-auto grid min-h-[calc(100vh-88px)] max-w-7xl items-center gap-14 px-6 py-16 lg:grid-cols-[1.08fr_.92fr] lg:px-8">
        <div><p className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-extrabold uppercase tracking-[.16em] text-white/75"><Users size={15} className="text-[#E34E26]" /> Para el equipo de organización</p><h1 className="text-5xl font-black leading-none tracking-[-.045em] sm:text-6xl lg:text-7xl">Cada donación,<span className="block text-[#E34E26]">mejor organizada.</span></h1><p className="mt-7 max-w-2xl text-lg font-medium leading-relaxed text-white/70 sm:text-xl">El espacio de trabajo de Acción del Sur para registrar donantes, ordenar insumos, controlar el inventario y coordinar los envíos de ayuda.</p><p className="mt-4 max-w-2xl text-base font-medium leading-relaxed text-white/55">Acción del Sur es una iniciativa de CGIC, una organización que impulsa soluciones frente a crisis climáticas y humanitarias desde la innovación, la tecnología y el territorio.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link to="/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#E34E26] px-6 py-3.5 font-extrabold shadow-xl">Ingresar al sistema <ArrowRight size={18} /></Link><a href="https://cgic-argentina.org/" target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/30 bg-white/5 px-6 py-3.5 font-extrabold hover:bg-white/10">Conocé más sobre CGIC <ExternalLink size={17} /></a><a href="#proceso" className="inline-flex items-center justify-center px-3 py-3.5 font-extrabold text-white/70 hover:text-white">Conocer el flujo</a></div><p className="mt-5 flex items-center gap-2 text-sm font-semibold text-white/45"><CheckCircle2 size={16} className="text-[#E34E26]" /> Acceso exclusivo para usuarios autorizados de CGIC</p></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 rotate-2 rounded-[2rem] border border-white/10 bg-white/[.035]" /><div className="relative rounded-[1.75rem] border border-white/15 bg-[#223140] p-6 shadow-2xl"><div className="mb-6 flex items-center justify-between border-b border-white/10 pb-5"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#E34E26]">Panel operativo</p><p className="mt-1 text-xl font-extrabold">Gestión de donaciones</p></div><LayoutDashboard className="text-[#E34E26]" /></div><div className="grid gap-3 sm:grid-cols-2">{steps.map(([title,, Icon], i) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.055] p-4"><div className="mb-5 flex justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E34E26]/15 text-[#E34E26]"><Icon size={20} /></span><span className="text-xs font-black text-white/25">0{i + 1}</span></div><p className="text-sm font-extrabold">{title}</p></div>)}</div><div className="mt-4 flex items-center gap-3 rounded-2xl bg-[#E34E26] p-4"><HandHeart /><div><b className="block text-sm">La ayuda empieza con un buen registro</b><small className="font-semibold text-white/70">Información clara para actuar mejor.</small></div></div></div></div>
      </div>
    </header>
    <main>
      <section id="funcionalidades" className="mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-black uppercase tracking-[.2em] text-[#E34E26]">Organización en un solo lugar</p><h2 className="mt-4 text-4xl font-black leading-tight sm:text-5xl">Un panel pensado para el trabajo cotidiano.</h2><p className="mt-5 text-lg font-medium leading-relaxed text-[#2E4053]/70">Diseñado para que voluntarios y responsables puedan cargar, consultar y actualizar la información de forma simple.</p></div><div className="grid gap-4 sm:grid-cols-3">{benefits.map(([title, text, Icon]) => <article key={title} className="rounded-2xl border border-[#D5DBDB] bg-white p-6 shadow-sm"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#1B2631] text-[#E34E26]"><Icon size={21} /></span><h3 className="mt-6 text-xl font-extrabold">{title}</h3><p className="mt-3 font-medium leading-relaxed text-[#2E4053]/65">{text}</p></article>)}</div></div></section>
      <section id="proceso" className="bg-white"><div className="mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28"><p className="text-sm font-black uppercase tracking-[.2em] text-[#E34E26]">Flujo de trabajo</p><h2 className="mt-4 max-w-3xl text-4xl font-black leading-tight sm:text-5xl">Del ingreso de la donación a la salida de la ayuda.</h2><p className="mt-5 text-lg font-medium text-[#2E4053]/65">Cuatro momentos conectados para acompañar la operación del equipo.</p><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{steps.map(([title, text, Icon], i) => <article key={title} className="relative overflow-hidden rounded-2xl border border-[#D5DBDB] bg-[#F4F6F7] p-6"><span className="absolute -right-1 -top-6 text-8xl font-black text-[#1B2631]/[.045]">0{i + 1}</span><div className="relative"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#1B2631] text-[#E34E26]"><Icon size={23} /></span><p className="mt-7 text-xs font-black uppercase tracking-[.2em] text-[#E34E26]">Paso {i + 1}</p><h3 className="mt-2 text-xl font-extrabold">{title}</h3><p className="mt-3 font-medium leading-relaxed text-[#2E4053]/65">{text}</p></div></article>)}</div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-20 lg:px-8"><div className="relative overflow-hidden rounded-[2rem] bg-[#1B2631] px-8 py-12 text-white lg:flex lg:items-center lg:justify-between lg:px-16"><div className="landing-grid absolute inset-0" /><div className="relative"><p className="text-sm font-black uppercase tracking-[.2em] text-[#E34E26]">Equipo CGIC</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">¿Listo para comenzar la jornada?</h2><p className="mt-4 text-lg font-medium text-white/65">Ingresá con tu usuario para acceder al panel de gestión.</p></div><Link to="/login" className="relative mt-8 inline-flex items-center gap-2 rounded-xl bg-[#E34E26] px-6 py-3.5 font-extrabold lg:mt-0">Iniciar sesión <ArrowRight size={18} /></Link></div></section>
    </main>
    <footer className="border-t border-[#D5DBDB] bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-6 py-8 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#1B2631] text-[#E34E26]"><HandHeart size={18} /></span><div><b className="block">Acción del Sur</b><small className="font-medium text-[#2E4053]/55">Una iniciativa de CGIC · Sistema interno de gestión logística</small></div></div><div className="flex gap-5"><a href="https://cgic-argentina.org/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-sm font-extrabold text-[#2E4053]">Sitio de CGIC <ExternalLink size={13} /></a><Link to="/login" className="text-sm font-extrabold text-[#E34E26]">Acceso al sistema</Link></div></div></footer>
  </div>;
}
